import type { WorkflowMetadata } from "./types";

/**
 * Builds a completed WorkflowMetadata object for the document creation workflow.
 * Call this after draftDocument succeeds in DocumentAssistantAgent.
 *
 * The "review_required" step is always a warning — documents generated by AI
 * must be reviewed before official use at St. Mary's.
 */
export function buildDocumentCreationWorkflow(
  agentDisplayName: string
): WorkflowMetadata {
  return {
    workflowId: crypto.randomUUID(),
    workflowType: "document_creation",
    status: "completed",
    agentDisplayName,
    steps: [
      {
        name: "request_received",
        label: "Request received",
        status: "completed",
        icon: "check",
      },
      {
        name: "agent_selected",
        label: `${agentDisplayName} selected`,
        status: "completed",
        icon: "check",
      },
      {
        name: "draft_generated",
        label: "Draft generated",
        status: "completed",
        icon: "check",
      },
      {
        name: "review_required",
        label: "Review required before official use",
        status: "warning",
        icon: "warning",
      },
      {
        name: "delivered",
        label: "Delivered",
        status: "completed",
        icon: "check",
      },
    ],
  };
}
