import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/session";
import nodemailer from "nodemailer";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { schedule, mode } = await req.json();
  if (!schedule) return NextResponse.json({ error: "No schedule content" }, { status: 400 });

  const to = session.email;
  if (!to) return NextResponse.json({ error: "No email in session" }, { status: 400 });

  const label = mode === "weekly" ? "Weekly" : "Daily";
  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long", month: "long", day: "numeric", year: "numeric",
  });

  const html = `
<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;background:#f4f4f4;padding:32px;">
<div style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;padding:32px;border:1px solid #e5e5e5;">
  <p style="margin:0 0 4px;font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:0.1em;">St. Mary's AI Workforce</p>
  <p style="margin:0 0 20px;font-size:22px;font-weight:bold;color:#0f172a;">📅 Your ${label} Schedule</p>
  <p style="margin:0 0 20px;font-size:13px;color:#64748b;">${today}</p>
  <div style="font-size:14px;line-height:1.8;color:#1e293b;white-space:pre-wrap;">${schedule.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\*(.*?)\*/g, '<em>$1</em>').replace(/^## (.*)/gm, '<h3 style="color:#0f766e;margin:16px 0 6px">$1</h3>').replace(/^# (.*)/gm, '<h2 style="color:#0f766e;margin:20px 0 8px">$1</h2>').replace(/^- (.*)/gm, '<li style="margin:4px 0">$1</li>')}</div>
  <p style="margin:32px 0 0;font-size:12px;color:#94a3b8;">Generated by St. Mary's AI Workforce · <a href="${process.env.APP_URL || "http://localhost:3000"}" style="color:#0f766e;">Open app</a></p>
</div>
</body></html>`.trim();

  const text = `Your ${label} Schedule — ${today}\n\n${schedule}`;

  try {
    const transport = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "smhdc-org.mail.protection.outlook.com",
      port: parseInt(process.env.SMTP_PORT || "25"),
      secure: false,
      tls: { rejectUnauthorized: false },
    });

    await transport.sendMail({
      from: `"St. Mary's AI Workforce" <${process.env.FROM_EMAIL || "noreply@smhdc.org"}>`,
      to,
      subject: `📅 Your ${label} Schedule — ${today}`,
      text,
      html,
    });

    return NextResponse.json({ success: true });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
