export type AgentDepartment =
  | "general"
  | "hr"
  | "it"
  | "leadership"
  | "operations";

export type AgentStatus =
  | "Active"
  | "Observe-only"
  | "Drafting"
  | "Needs approval"
  | "Disabled"
  | "Future";

export type AgentRiskLevel = "Low" | "Medium" | "High";

export type AgentRegistryItem = {
  name: string;
  displayName: string;
  icon: string;
  department: AgentDepartment;
  departmentLabel: string;
  purpose: string;
  status: AgentStatus;
  riskLevel: AgentRiskLevel;
  tools: string[];
  workflows: string[];
  implemented: boolean;
  tasks: string[];
  sources: string[];
  responsibilities: string[];
  examplePrompts: string[];
  safetyNotes: string[];
};

export const departmentOrder: AgentDepartment[] = [
  "general",
  "hr",
  "it",
  "leadership",
  "operations",
];

export const departmentLabels: Record<AgentDepartment, string> = {
  general: "General / Knowledge",
  hr: "HR",
  it: "IT",
  leadership: "Leadership",
  operations: "Operations",
};

export const agentRegistry: AgentRegistryItem[] = [
  {
    name: "policy",
    displayName: "Policy Agent",
    icon: "📋",
    department: "general",
    departmentLabel: departmentLabels.general,
    purpose: "Answers policy, SOP, procedure, attendance, handbook, guideline, and internal process questions from approved internal knowledge.",
    status: "Active",
    riskLevel: "Medium",
    tools: ["Internal knowledge retrieval", "Source confidence checks"],
    workflows: ["Policy lookup", "SOP explanation", "Internal source summary"],
    implemented: true,
    tasks: ["Answer policy and procedure questions", "Summarize SOPs", "Explain attendance and handbook rules", "Find approved internal guidelines"],
    sources: ["SharePoint HR Policies", "St. Mary's Staff Handbook", "Internal SOPs"],
    responsibilities: ["Look up approved policies from internal documents", "Summarize relevant sections clearly", "Flag when no approved source is found", "Cite document titles in every response"],
    examplePrompts: ["What is the attendance policy?", "How do I request FMLA leave?", "What is the corrective action process?", "What are the rules around overtime?"],
    safetyNotes: ["Does not invent policy details", "Always cites source document", "Will not answer resident-specific or clinical questions", "Flags missing sources explicitly"],
  },
  {
    name: "medical_education",
    displayName: "Medical Education Agent",
    icon: "🏥",
    department: "general",
    departmentLabel: departmentLabels.general,
    purpose: "Classifies general health education questions and refuses resident-specific, PHI, diagnostic, medication, or urgent clinical requests.",
    status: "Active",
    riskLevel: "High",
    tools: ["Safety classification"],
    workflows: ["General health education triage", "Clinical safety refusal"],
    implemented: true,
    tasks: ["Answer general health education questions", "Refuse resident-specific or clinical requests", "Redirect urgent clinical issues to nursing staff"],
    sources: ["General medical education knowledge"],
    responsibilities: ["Answer only general educational health questions", "Refuse all PHI, resident-specific, and diagnostic requests", "Escalate urgent or safety-critical questions immediately"],
    examplePrompts: ["What is a pressure ulcer?", "What does HIPAA protect?", "What is the purpose of a care plan?"],
    safetyNotes: ["Will never answer questions about specific residents", "Refuses medication dosage or clinical advice", "Escalates all urgent clinical concerns to nursing staff", "PHI is automatically scrubbed before processing"],
  },
  {
    name: "document_assistant",
    displayName: "HR Agent",
    icon: "👥",
    department: "hr",
    departmentLabel: departmentLabels.hr,
    purpose: "Drafts staff-facing documents, emails, checklists, onboarding content, executive summaries, and operational templates.",
    status: "Active",
    riskLevel: "Medium",
    tools: ["Draft document"],
    workflows: ["Email drafting", "Checklist generation", "Document summaries"],
    implemented: true,
    tasks: ["Draft professional emails", "Create onboarding checklists", "Generate SOPs and procedure templates", "Write executive summaries", "Build request forms and operational documents"],
    sources: ["Staff-provided context", "Internal policy documents when available"],
    responsibilities: ["Produce editable professional drafts", "Use placeholders for names, dates, and departments", "Avoid inventing official policy language", "Format documents clearly with sections and headings"],
    examplePrompts: ["Draft an email to staff about the new attendance policy", "Create an onboarding checklist for a new CNA", "Write an SOP for medication administration sign-off", "Draft a professional email requesting PTO"],
    safetyNotes: ["Marks all output as drafts requiring human review", "Does not present generated content as approved policy", "Does not include PHI in generated documents", "Flags when policy verification is needed"],
  },
  {
    name: "onboarding",
    displayName: "Onboarding Agent",
    icon: "🧭",
    department: "hr",
    departmentLabel: departmentLabels.hr,
    purpose: "Future specialist for role-based onboarding plans, training paths, system access checklists, and new-hire readiness.",
    status: "Future",
    riskLevel: "Medium",
    tools: [],
    workflows: ["New-hire onboarding", "Training path planning"],
    implemented: false,
    tasks: ["Generate role-specific onboarding plans", "Create system access checklists", "Plan training sequences", "Track new-hire readiness"],
    sources: ["HR policies", "Role definitions", "System access requirements"],
    responsibilities: ["Build onboarding plans by role and department", "List required system access and training", "Organize onboarding by timing and workstream"],
    examplePrompts: ["Create an onboarding plan for a new RN", "What systems does a new CNA need access to?", "Generate a 30-60-90 day onboarding checklist"],
    safetyNotes: ["Will be reviewed by HR before deployment", "Cannot grant system access directly"],
  },
  {
    name: "it_support",
    displayName: "IT Support Agent",
    icon: "🖥",
    department: "it",
    departmentLabel: departmentLabels.it,
    purpose: "Routes IT troubleshooting questions for CareTracker, SigmaCare, Microsoft 365, UniFi, printers, login, and access issues.",
    status: "Active",
    riskLevel: "Medium",
    tools: ["IT knowledge search"],
    workflows: ["Troubleshooting guidance", "System access triage"],
    implemented: true,
    tasks: ["Troubleshoot CareTracker and SigmaCare issues", "Guide Microsoft 365 and Outlook problems", "Help with printer, scanner, and copier issues", "Assist with password resets and login problems", "Triage network and Wi-Fi issues"],
    sources: ["IT knowledge base", "System documentation", "St. Mary's IT procedures"],
    responsibilities: ["Provide step-by-step troubleshooting guidance", "Identify when issues need hands-on IT escalation", "Document what to capture before escalating", "Route door access and badge issues to IT/Security"],
    examplePrompts: ["CareTracker won't load for me", "My Outlook keeps crashing", "Printer in the east wing is offline", "I forgot my Microsoft 365 password", "My network drive is not mapped"],
    safetyNotes: ["Does not have access to reset passwords directly", "Escalates all access and security incidents", "Does not handle clinical system data", "IT Support contact provided for all escalations"],
  },
  {
    name: "issuetrak_ticket",
    displayName: "Issuetrak Ticket Agent",
    icon: "🎫",
    department: "it",
    departmentLabel: departmentLabels.it,
    purpose: "Future specialist for summarizing support issues and preparing ticket-ready intake details.",
    status: "Future",
    riskLevel: "Medium",
    tools: [],
    workflows: ["Ticket drafting", "Issue intake"],
    implemented: false,
    tasks: ["Summarize IT support issues into ticket format", "Collect issue details, location, and urgency", "Submit or prepare Issuetrak tickets"],
    sources: ["Staff-provided issue description", "Issuetrak ticket system"],
    responsibilities: ["Gather issue details systematically", "Format ticket submissions clearly", "Route to correct Issuetrak category"],
    examplePrompts: ["Submit a ticket for my broken printer", "Create an IT ticket for a network issue in Room 12"],
    safetyNotes: ["Pending Issuetrak API approval", "Will require manager authorization before live ticket submission"],
  },
  {
    name: "account_access",
    displayName: "Account Access Agent",
    icon: "🔐",
    department: "it",
    departmentLabel: departmentLabels.it,
    purpose: "Future specialist for read-only account access triage, role mapping, and access request preparation.",
    status: "Future",
    riskLevel: "High",
    tools: [],
    workflows: ["Access review", "Role request preparation"],
    implemented: false,
    tasks: ["Review account access needs by role", "Prepare access request documentation", "Map job roles to required system permissions"],
    sources: ["IT role definitions", "System access matrix"],
    responsibilities: ["Read-only access review only", "Prepare access requests for IT review", "Document current vs required access"],
    examplePrompts: ["What access does a new charge nurse need?", "Prepare an access request for a new admissions coordinator"],
    safetyNotes: ["Read-only — cannot grant or modify access", "All access changes require IT and manager approval", "High risk: subject to strict audit logging"],
  },
  {
    name: "executive",
    displayName: "Executive Agent",
    icon: "📊",
    department: "leadership",
    departmentLabel: departmentLabels.leadership,
    purpose: "Helps leadership frame source-backed summaries, risks, operational overviews, briefings, and recommended next actions.",
    status: "Active",
    riskLevel: "Medium",
    tools: ["Internal knowledge retrieval", "Executive summary formatting"],
    workflows: ["Executive briefing", "Risk summary", "Operational overview"],
    implemented: true,
    tasks: ["Write executive briefings from internal documents", "Summarize operational risks", "Prepare leadership-ready summaries", "Frame recommended next actions for decision-makers"],
    sources: ["SharePoint policies", "Internal knowledge base", "Provided operational context"],
    responsibilities: ["Write for CEO, CFO, HR, and department leadership", "Lead with key points and recommended actions", "Include risk levels and operational impact", "Cite sources used in every briefing"],
    examplePrompts: ["Summarize our attendance policy for leadership", "Give me an executive overview of our retention policy", "What are the key risks in our current onboarding process?", "Prepare a briefing on our IT support escalation process"],
    safetyNotes: ["Does not make decisions on behalf of leadership", "All summaries should be verified before formal use", "Does not include PHI in briefings", "Flags when approved internal source is not available"],
  },
  {
    name: "operations",
    displayName: "Operations Agent",
    icon: "⚙",
    department: "operations",
    departmentLabel: departmentLabels.operations,
    purpose: "Future specialist for operational playbooks, process coordination, and cross-department task planning.",
    status: "Future",
    riskLevel: "Medium",
    tools: [],
    workflows: ["Operations planning", "Process coordination"],
    implemented: false,
    tasks: ["Build operational playbooks", "Coordinate cross-department tasks", "Summarize operational process gaps"],
    sources: ["Internal SOPs", "Cross-department process documentation"],
    responsibilities: ["Organize operational tasks by department and timeline", "Identify process owners and dependencies"],
    examplePrompts: ["Build a playbook for new resident intake", "What are the steps for end-of-quarter reporting?"],
    safetyNotes: ["Future agent — pending planning and approval"],
  },
  {
    name: "sharepoint",
    displayName: "SharePoint Agent",
    icon: "🗂",
    department: "operations",
    departmentLabel: departmentLabels.operations,
    purpose: "Future specialist for SharePoint content discovery, sync health summaries, and source-of-truth stewardship.",
    status: "Future",
    riskLevel: "Medium",
    tools: [],
    workflows: ["Knowledge sync review", "Content inventory"],
    implemented: false,
    tasks: ["Report SharePoint sync health", "Identify outdated or unindexed documents", "Summarize knowledge base coverage"],
    sources: ["SharePoint document library", "Sync status logs"],
    responsibilities: ["Monitor knowledge base freshness", "Flag documents needing reindexing", "Report on knowledge coverage gaps"],
    examplePrompts: ["What documents were synced from SharePoint this week?", "Are there any documents that failed to index?"],
    safetyNotes: ["Read-only access to sync logs", "Cannot modify SharePoint content directly"],
  },
  {
    name: "agenda",
    displayName: "Agenda Agent",
    icon: "🗓",
    department: "operations",
    departmentLabel: departmentLabels.operations,
    purpose: "Future specialist for agendas, meeting prep, follow-up summaries, and operational action registers.",
    status: "Future",
    riskLevel: "Low",
    tools: [],
    workflows: ["Agenda drafting", "Follow-up planning"],
    implemented: false,
    tasks: ["Draft meeting agendas", "Summarize follow-up action items", "Build operational action registers"],
    sources: ["Provided meeting notes and context"],
    responsibilities: ["Organize agendas by topic and owner", "Capture action items with deadlines and owners"],
    examplePrompts: ["Draft an agenda for our weekly leadership meeting", "Summarize action items from today's standup"],
    safetyNotes: ["Low risk — document generation only", "Does not send or schedule meetings directly"],
  },

  {
    name: "compliance_survey",
    displayName: "Compliance & Survey Agent",
    icon: "🏛",
    department: "general",
    departmentLabel: departmentLabels.general,
    purpose: "Answers CMS, state survey, deficiency, plan of correction, and audit readiness questions.",
    status: "Active",
    riskLevel: "High",
    tools: ["Internal knowledge retrieval"],
    workflows: ["Survey prep", "Deficiency response", "Compliance audit"],
    implemented: true,
    tasks: ["Answer CMS survey prep questions", "Explain F-tags", "Guide plan of correction drafting", "Review audit readiness"],
    sources: ["CMS regulations", "State survey guidance", "Internal compliance policies"],
    responsibilities: ["Answer regulatory questions from internal documents", "Guide survey readiness", "Explain deficiency correction steps"],
    examplePrompts: ["How do we prepare for a CMS survey?", "What is F-tag 689?", "How do we write a plan of correction?"],
    safetyNotes: ["Does not provide legal determinations", "Always recommend Compliance Officer review", "High risk — cite source in every response"],
  },
  {
    name: "payroll_benefits",
    displayName: "Payroll & Benefits Agent",
    icon: "💰",
    department: "hr",
    departmentLabel: departmentLabels.hr,
    purpose: "Answers pay, Paylocity, PTO, sick leave, benefits enrollment, health insurance, 401k, and timecard questions.",
    status: "Active",
    riskLevel: "Medium",
    tools: ["Internal knowledge retrieval"],
    workflows: ["PTO inquiry", "Benefits explanation", "Payroll issue triage"],
    implemented: true,
    tasks: ["Explain PTO and sick leave", "Guide benefits enrollment", "Help with timecard corrections", "Answer pay period questions"],
    sources: ["HR benefits guides", "Paylocity documentation", "Staff handbook"],
    responsibilities: ["Answer payroll and benefits questions", "Guide Paylocity steps", "Escalate pay discrepancies to HR"],
    examplePrompts: ["How do I request PTO in Paylocity?", "When does open enrollment close?", "How do I fix a timecard error?"],
    safetyNotes: ["Cannot process payroll changes", "Pay discrepancies escalated to HR/Payroll", "No access to individual employee records"],
  },
  {
    name: "staffing",
    displayName: "Staffing Agent",
    icon: "🗓",
    department: "hr",
    departmentLabel: departmentLabels.hr,
    purpose: "Answers staffing, scheduling, shift coverage, call-out, overtime, and minimum staffing ratio questions.",
    status: "Active",
    riskLevel: "Medium",
    tools: ["Internal knowledge retrieval"],
    workflows: ["Shift coverage inquiry", "Call-out procedure", "Overtime policy lookup"],
    implemented: true,
    tasks: ["Explain call-out procedures", "Answer overtime questions", "Guide shift coverage requests", "Explain per diem policies"],
    sources: ["HR staffing policies", "Staff handbook", "Scheduling procedures"],
    responsibilities: ["Answer scheduling policy questions", "Guide call-out procedures", "Escalate coverage issues to charge nurse"],
    examplePrompts: ["What is the call-out procedure?", "How many call-outs before corrective action?", "What is the minimum staffing ratio?"],
    safetyNotes: ["Cannot approve schedule changes", "Staffing shortages escalated to supervisor", "No access to live scheduling systems"],
  },
  {
    name: "training_education",
    displayName: "Training & Education Agent",
    icon: "🎓",
    department: "hr",
    departmentLabel: departmentLabels.hr,
    purpose: "Answers mandatory training requirements, in-service education, competency checks, orientation, and certification questions.",
    status: "Active",
    riskLevel: "Low",
    tools: ["Internal knowledge retrieval"],
    workflows: ["Training requirements lookup", "In-service scheduling", "Certification guidance"],
    implemented: true,
    tasks: ["Explain mandatory annual training", "Answer in-service questions", "Guide new hire orientation", "Explain CEU requirements"],
    sources: ["Training policies", "Orientation guides", "Compliance training requirements"],
    responsibilities: ["Answer training requirement questions", "List required annual trainings by role", "Guide staff to complete outstanding training"],
    examplePrompts: ["What mandatory training is due this year?", "How do I complete fire safety training?", "What is required for new CNA orientation?"],
    safetyNotes: ["Cannot mark training complete in any system", "Training compliance tracked by HR and Education Department"],
  },
  {
    name: "facilities",
    displayName: "Facilities Agent",
    icon: "🔧",
    department: "operations",
    departmentLabel: departmentLabels.operations,
    purpose: "Helps report building, HVAC, plumbing, and electrical issues and guides work order submission.",
    status: "Active",
    riskLevel: "Low",
    tools: ["Internal knowledge retrieval"],
    workflows: ["Work order intake", "Maintenance issue guidance", "Facilities procedure lookup"],
    implemented: true,
    tasks: ["Guide work order submission", "Answer HVAC and building questions", "Explain maintenance request process"],
    sources: ["Facilities procedures", "Work order guidelines", "Building maintenance SOPs"],
    responsibilities: ["Guide maintenance issue reporting", "Explain facilities procedures", "Escalate safety issues immediately"],
    examplePrompts: ["How do I submit a maintenance request?", "The heat is not working — what do I do?", "Who do I call for a water leak?"],
    safetyNotes: ["Cannot submit work orders directly", "Safety hazards escalated to Maintenance and Supervisor", "Call 911 for life-safety emergencies"],
  },
  {
    name: "family_communications",
    displayName: "Family Communications Agent",
    icon: "💌",
    department: "hr",
    departmentLabel: departmentLabels.hr,
    purpose: "Drafts professional letters and communications to resident families for admissions, updates, meetings, and notices.",
    status: "Active",
    riskLevel: "Medium",
    tools: ["Draft document"],
    workflows: ["Family letter drafting", "Admission notice", "Family update communications"],
    implemented: true,
    tasks: ["Draft family update letters", "Create admission communications", "Write family meeting notices", "Draft family announcements"],
    sources: ["Staff-provided context", "Communication templates"],
    responsibilities: ["Draft professional family communications", "Include placeholders for specific details", "Never include PHI", "Require staff review before sending"],
    examplePrompts: ["Draft a letter to a family about our visiting policy", "Write a family notice about the holiday schedule", "Draft an admission welcome letter"],
    safetyNotes: ["Never includes resident PHI or clinical details", "All letters must be reviewed before sending", "Clinical updates require nursing involvement"],
  },
  {
    name: "quality_assurance",
    displayName: "Quality Assurance Agent",
    icon: "✅",
    department: "operations",
    departmentLabel: departmentLabels.operations,
    purpose: "Assists with incident report drafting, QAPI questions, grievance handling, and quality improvement documentation.",
    status: "Active",
    riskLevel: "High",
    tools: ["Internal knowledge retrieval", "Draft document"],
    workflows: ["Incident report intake", "QAPI guidance", "Grievance procedure lookup"],
    implemented: true,
    tasks: ["Guide incident report completion", "Answer QAPI questions", "Explain grievance procedures", "Help draft root cause analysis"],
    sources: ["QA policies", "Incident reporting procedures", "QAPI guidelines"],
    responsibilities: ["Guide incident documentation", "Explain QAPI steps", "Escalate serious incidents immediately"],
    examplePrompts: ["How do I complete a fall incident report?", "What is our grievance process?", "What does QAPI stand for?", "How do I document a near miss?"],
    safetyNotes: ["Serious incidents escalated to DON and Administrator immediately", "No clinical or liability determinations", "All incident reports require supervisor review"],
  },
  {
    name: "vendor_supply",
    displayName: "Vendor & Supply Agent",
    icon: "📦",
    department: "operations",
    departmentLabel: departmentLabels.operations,
    purpose: "Answers approved vendor contacts, supply orders, PPE, medical supplies, and procurement procedure questions.",
    status: "Active",
    riskLevel: "Low",
    tools: ["Internal knowledge retrieval"],
    workflows: ["Supply request guidance", "Vendor contact lookup", "Procurement procedure"],
    implemented: true,
    tasks: ["Answer supply ordering questions", "Find vendor contacts", "Explain purchase order process", "Guide PPE requests"],
    sources: ["Vendor directories", "Supply ordering procedures", "Procurement policies"],
    responsibilities: ["Answer supply and vendor questions", "Guide ordering procedures", "Escalate supply shortages to department head"],
    examplePrompts: ["Who is our medical supply vendor?", "How do I order more gloves?", "What is the purchase order process?", "Who handles linen shortages?"],
    safetyNotes: ["Cannot place orders directly", "PPE shortages treated as urgent", "Shortages escalated to department supervisor"],
  },

];
